### ISSUE TITLE
Error downloading the fungal database.

### ISSUE THREAD

**Issue by abdeljalil-senhaji** [glarue/jgi-query#16]
Hello @glarue 

I am launching the script to retrieve all the fungal assembly sequences in fasta format, but it is showing me this error:

`python3 jgi-query.py fungi

Retrieving information from JGI for query 'fungi' using command 'curl 'https://genome.jgi.doe.gov/portal/ext-api/downloads/get-directory? 
organism=fungi' -L -b cookies > fungi_jgi_index.xml'

% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                             Dload  Upload   Total   Spent    Left  Speed
 100    92    0    92    0     0      0      0 --:--:--  0:10:00 --:--:--    28

Traceback (most recent call last):
   File /JGI-db/jgi-query-main/jgi-query.py", line 1151, in <module>
   if not any(v["results"] for v in list(file_list.values())):
AttributeError: 'NoneType' object has no attribute 'values'`

Do you have any idea how to download all the fungal genome sequences?

**Comment by glarue** [comment]
Hi @abdeljalil-senhaji, not sure if you saw my response to your earlier issue on the same topic? https://github.com/glarue/jgi-query/issues/15

**Comment by glarue** [comment]
Resolved in https://github.com/glarue/jgi-query/issues/15#issuecomment-1557251215
