### ISSUE TITLE
Files on tape can't be downloaded

### ISSUE THREAD

**Issue by vtorda** [glarue/jgi-query#17]
In many cases, files are stored on tape, and the download seems to have a problem.  I am unfamiliar with Python to make a pull request, but one partial workaround could be if the same file can be found on tape and hard drive, the file on the hard drive is selected. Thanks if you have time to check this!

**Comment by glarue** [comment]
Sorry for delayed response @vtorda. I believe this is an issue which has come up before and is related to the way JGI stores its archival data. As far as I'm aware, there is no redundancy between less-cold storage and tape archives; if it's on tape, there isn't an alternative version to grab.

The solution to this has historically been to try the request, and then wait a frustratingly indeterminate amount of time before trying again (at which point the data may have been pulled from the archive and will be retrievable). If you can give me a specific example of a query that's giving you problems I can see if I can diagnose it further. Alternatively, JGI now has a number of other methods to request data that might be more streamlined in this case.

**Comment by glarue** [comment]
Closing this due to lack of response; please open a new issue if this is still giving you problems.
