### ISSUE TITLE
10 Minute time limit

### ISSUE THREAD

**Issue by ncolaian** [glarue/jgi-query#3]
So first off thanks for this tool, it's very useful.

My Problem:
I am trying to create an XML file from a very large database on jgi, and there seems to be a 10 minute runtime limit. Is this something built in or can it be changed?

Thanks

**Comment by glarue** [comment]
Hey ncolaian,

So, is the request timing out while processing the XML file, or while downloading data files? Can you provide me with the query you're using?

It's not a built-in limit that I've imposed, and there doesn't seem to be anything in the cURL documentation suggesting a timeout once a connection has actually been established with the host. It's possible that cURL is unable to reach the server and is timing out for that reason, but I'd have to try it myself to figure that out.

**Comment by ncolaian** [comment]
The request times out while processing the XML file. I have been querying the fungal database (Using fungi as my query). The weird part about the time out is that it will occasionally work if it takes under 10 minutes, however if it reaches the 10 minute point it will produce an error every single time.

**Comment by glarue** [comment]
@ncolaian can you please provide the exact error output that you're getting? I can't recreate it on my end, perhaps due to higher bandwidth. Thanks!

**Comment by ncolaian** [comment]
The internet seems to be working well today, and I haven't received the same error yet because I haven't hit the 10 minute mark when running the query. If it happens again though I will post the error.


-ncolaian

________________________________

**Comment by glarue** [comment]
@ncolaian okay please do, as it's likely to affect someone else is the future. Closing for now.

**Comment by ncolaian** [comment]
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   107    0   107    0     0    139      0 --:--:-- --:--:-- --:--:--  104k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   441    0   441    0     0      0      0 --:--:--  0:10:00 --:--:--   107
Cannot parse XML file or no organism match found.
Ensure remote file exists and has content at the following address:
http://genome.jgi.doe.gov/ext-api/downloads/get-directory?organism=fungi
Removing temp files and exiting

Here is the error.

**Comment by glarue** [comment]
Hey @ncolaian, see my recent commit moving the queries from http to https; it may help with the problem you were having.
