### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by poojasingh09** [glarue/jgi-query#6]
Hello, when I use python3 ./jgi-query/jgi-query.py --xml get-directory.xml to download files from JGI genome portal,
I get the following download error. Do you know what the issue could be?

Thanks!
______________________________________________________
Downloading '7393.1.70539.TCGAAG.fastq.gz' using command:
curl -m 120 'https://genome.jgi.doe.gov/portal/ext-api/downloads/get_tape_file?blocking=true&url=/Poptrisequencing_78/download/_JAMO/5254b441067c0136350e4f73/7393.1.70539.TCGAAG.fastq.gz' -b cookies > 7393.1.70539.TCGAAG.fastq.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Trying '7393.1.70539.TCGAAG.fastq.gz' again due to download error (1/4):

**Comment by glarue** [comment]
Hi @poojasingh09, sorry for the delay - an email filter caught this issue notification accidentally.

Can you give me more information about the XML file (how was it generated, etc)? Was this an XML file that `jgi-query` created during a previous run?

Also, did you let `jgi-query` retry the specific download mentioned above? It makes four separate attempts in an effort to overcome some of the more common reasons a file won't download. Even if it fails all four attempts, it will occasionally work if you try it again afterward—this has to do with how JGI stores certain files as tape archives, which are pulled out of the archive when requested but are often delayed for that reason.

**Comment by glarue** [comment]
@poojasingh09 I'm going to close this now for inactivity, but if this is still an issue for you please feel free to update.

**Comment by raulmireles** [comment]
Hi @glarue,

I'm getting this error very often and almost every time I run the script.

curl: (28) Operation timed out after 120000 milliseconds with 0 bytes received

Is it because of my internet connection? What could you suggest to fix it?

**Comment by glarue** [comment]
Hi @raulmireles,

The first thing to do would be to see if I can reproduce the problem. Can you first create a new issue on GitHub with an example of the command that's giving you trouble? I will then check it on my end.
