### ISSUE TITLE
Downloading error: curl: (28)

### ISSUE THREAD

**Issue by raulmireles** [glarue/jgi-query#8]
Hi @glarue 
I'm running the script in a remote server to download the *.tar.gz files from bacterial groups (as suggested here: https://github.com/glarue/jgi-query/issues/4). 

Every time I run this command (starts in tar.gz not shown):
 
python3 jgi-query.py tenericutes -r '.*tar.gz.*' --retry_n 0 -c

I get something like this, on every single genome ID contained in tenericutes:

Downloading '2582580514.tar.gz' using command:
curl -m 120 'https://genome.jgi.doe.gov/portal/ext-api/downloads/get_tape_file?blocking=true&url=/Comgenmetab10417/download/_JAMO/53e5233f0d87856ba82b2ddc/2582580514.tar.gz' -b cookies > 2582580514.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:59 --:--:--     0
curl: (28) Operation timed out after 120000 milliseconds with 0 bytes received

I also run it with default retry number (4) and it happens the same. I hope you can guide me through this.

Many thanks in advance

**Comment by glarue** [comment]
Hmm, I'm not able to exactly recreate your issue—to begin, the regex query you listed above doesn't return any files when I run it; are you sure that's exactly what you're running?

When I tested the specific file that it errored out on above, it worked for me:

```
~ jgi-query.py tenericutes -r '.*2582580514\.tar\.gz'                                                                              1 ✘  1m 29s  
Retrieving information from JGI for query 'tenericutes' using command 'curl 'https://genome.jgi.doe.gov/portal/ext-api/downloads/get-directory?organism=tenericutes' -L -b cookies > tenericutes_jgi_index.xml'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2581k    0 2581k    0     0   618k      0 --:--:--  0:00:04 --:--:--  619k


QUERY RESULTS FOR 'tenericutes'

Total download size for 1 files: 901.38 KB
Downloading '2582580514.tar.gz' using command:
curl -m 120 'https://genome.jgi.doe.gov/portal/ext-api/downloads/get_tape_file?blocking=true&url=/Comgenmetab10417/download/_JAMO/53e5233f0d87856ba82b2ddc/2582580514.tar.gz' -b cookies > 2582580514.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  901k    0  901k    0     0  1450k      0 --:--:-- --:--:-- --:--:-- 1451k
Finished downloading 1 files.
Removing temp files and exiting
```
Occasionally, this sort of things happens with tape files (see https://github.com/glarue/jgi-query/issues/5#issuecomment-378365665), where multiple queries are needed to actually have the JGI backend load the file for download.

My recommendation would be to leave the default value for `--retry_n`, try running the command and then, after ~10 min, try running it again. Seems silly, but this often works as the files have had time to load. Let me know if that doesn't work/there are any other issues.

**Comment by raulmireles** [comment]
Now it's working. The problem was solved by writing the correct syntax in -r at the initial command instructions.

Thanks @glarue
